import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { 
  FileText, 
  AlertTriangle, 
  CheckCircle2, 
  AlertCircle,
  Download,
  Share2,
  Calendar,
  MapPin,
  Phone
} from "lucide-react";
import { cn } from "@/lib/utils";
import { pdfReportService } from "@/utils/pdfService";

export interface ScreeningReportData {
  riskLevel: "Low" | "Medium" | "High" | "Uncertain";
  imageSummary: string;
  questionnaireSummary: string;
  combinedAssessment: string;
  recommendation: string;
  disclaimer: string;
  riskFactors: string[];
  protectiveFactors: string[];
  nextSteps: string[];
  urgencyLevel: "routine" | "soon" | "urgent";
  generatedAt: string;
}

interface ScreeningReportProps {
  reportData: ScreeningReportData;
  onNewScreening: () => void;
  onFindMedicalHelp: () => void;
}

export function ScreeningReport({ reportData, onNewScreening, onFindMedicalHelp }: ScreeningReportProps) {
  const getRiskStyles = (riskLevel: string) => {
    switch (riskLevel) {
      case "Low":
        return {
          bg: "bg-green-50 dark:bg-green-950",
          border: "border-green-200 dark:border-green-800",
          badge: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
          icon: CheckCircle2,
          iconColor: "text-green-600 dark:text-green-400"
        };
      case "Medium":
        return {
          bg: "bg-yellow-50 dark:bg-yellow-950",
          border: "border-yellow-200 dark:border-yellow-800",
          badge: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
          icon: AlertTriangle,
          iconColor: "text-yellow-600 dark:text-yellow-400"
        };
      case "High":
        return {
          bg: "bg-red-50 dark:bg-red-950",
          border: "border-red-200 dark:border-red-800",
          badge: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
          icon: AlertCircle,
          iconColor: "text-red-600 dark:text-red-400"
        };
      default:
        return {
          bg: "bg-gray-50 dark:bg-gray-950",
          border: "border-gray-200 dark:border-gray-800",
          badge: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200",
          icon: AlertTriangle,
          iconColor: "text-gray-600 dark:text-gray-400"
        };
    }
  };

  const getUrgencyMessage = (urgencyLevel: string) => {
    switch (urgencyLevel) {
      case "urgent":
        return {
          message: "Schedule dermatologist appointment within 1-2 days",
          color: "text-red-600 dark:text-red-400",
          bg: "bg-red-50 dark:bg-red-950"
        };
      case "soon":
        return {
          message: "Schedule dermatologist appointment within 2-4 weeks",
          color: "text-yellow-600 dark:text-yellow-400",
          bg: "bg-yellow-50 dark:bg-yellow-950"
        };
      default:
        return {
          message: "Continue routine monitoring and annual check-ups",
          color: "text-green-600 dark:text-green-400",
          bg: "bg-green-50 dark:bg-green-950"
        };
    }
  };

  const styles = getRiskStyles(reportData.riskLevel);
  const urgency = getUrgencyMessage(reportData.urgencyLevel);
  const RiskIcon = styles.icon;

  const handleDownloadReport = () => {
    try {
      // Generate and download PDF report
      pdfReportService.generateScreeningReportPDF(reportData);
    } catch (error) {
      console.error('Error generating PDF:', error);
      // Fallback to text download if PDF generation fails
      const reportText = `
SKIN CANCER SCREENING REPORT
Generated: ${new Date(reportData.generatedAt).toLocaleString()}

RISK ASSESSMENT: ${reportData.riskLevel}

IMAGE ANALYSIS SUMMARY:
${reportData.imageSummary}

QUESTIONNAIRE FINDINGS:
${reportData.questionnaireSummary}

COMBINED ASSESSMENT:
${reportData.combinedAssessment}

RECOMMENDATIONS:
${reportData.recommendation}

NEXT STEPS:
${reportData.nextSteps.map(step => `• ${step}`).join('\n')}

RISK FACTORS IDENTIFIED:
${reportData.riskFactors.map(factor => `• ${factor}`).join('\n')}

PROTECTIVE FACTORS:
${reportData.protectiveFactors.map(factor => `• ${factor}`).join('\n')}

MEDICAL DISCLAIMER:
${reportData.disclaimer}

---
This report was generated by an AI screening tool and is for educational purposes only.
Always consult with qualified healthcare professionals for medical advice.
      `.trim();

      const blob = new Blob([reportText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `skin-screening-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full max-w-4xl mx-auto space-y-6"
    >
      {/* Header Card */}
      <Card className={cn("shadow-lg", styles.bg, styles.border)}>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <RiskIcon className={cn("w-8 h-8", styles.iconColor)} />
              <div>
                <CardTitle className="text-2xl">Screening Report</CardTitle>
                <CardDescription className="text-base">
                  AI-powered skin cancer screening assessment
                </CardDescription>
              </div>
            </div>
            <Badge className={styles.badge} variant="secondary">
              {reportData.riskLevel} Risk
            </Badge>
          </div>
          
          <div className="text-sm text-muted-foreground">
            Generated on {new Date(reportData.generatedAt).toLocaleString()}
          </div>
        </CardHeader>
      </Card>

      {/* Urgency Alert */}
      <Card className={cn("shadow-md", urgency.bg)}>
        <CardContent className="pt-6">
          <div className="flex items-center gap-3">
            <Calendar className={cn("w-5 h-5", urgency.color)} />
            <div>
              <p className={cn("font-medium", urgency.color)}>
                Recommended Timeline
              </p>
              <p className="text-sm text-muted-foreground">
                {urgency.message}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Main Assessment */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Image Analysis */}
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <FileText className="w-5 h-5" />
              Image Analysis
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">{reportData.imageSummary}</p>
          </CardContent>
        </Card>

        {/* Questionnaire Findings */}
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <FileText className="w-5 h-5" />
              Questionnaire Findings
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">{reportData.questionnaireSummary}</p>
          </CardContent>
        </Card>
      </div>

      {/* Combined Assessment */}
      <Card className="shadow-md">
        <CardHeader>
          <CardTitle className="text-lg">Combined Risk Assessment</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed mb-4">{reportData.combinedAssessment}</p>
          
          <div className="grid md:grid-cols-2 gap-4">
            {/* Risk Factors */}
            {reportData.riskFactors.length > 0 && (
              <div>
                <h4 className="font-medium text-sm mb-2 text-red-600 dark:text-red-400">
                  Risk Factors Identified:
                </h4>
                <ul className="space-y-1">
                  {reportData.riskFactors.map((factor, index) => (
                    <li key={index} className="text-sm flex items-start gap-2">
                      <AlertTriangle className="w-3 h-3 mt-0.5 text-red-500 flex-shrink-0" />
                      {factor}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Protective Factors */}
            {reportData.protectiveFactors.length > 0 && (
              <div>
                <h4 className="font-medium text-sm mb-2 text-green-600 dark:text-green-400">
                  Protective Factors:
                </h4>
                <ul className="space-y-1">
                  {reportData.protectiveFactors.map((factor, index) => (
                    <li key={index} className="text-sm flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 mt-0.5 text-green-500 flex-shrink-0" />
                      {factor}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Recommendations */}
      <Card className="shadow-md">
        <CardHeader>
          <CardTitle className="text-lg">Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed mb-4">{reportData.recommendation}</p>
          
          <div>
            <h4 className="font-medium text-sm mb-2">Next Steps:</h4>
            <ul className="space-y-2">
              {reportData.nextSteps.map((step, index) => (
                <li key={index} className="text-sm flex items-start gap-2">
                  <div className="w-5 h-5 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-medium mt-0.5 flex-shrink-0">
                    {index + 1}
                  </div>
                  {step}
                </li>
              ))}
            </ul>
          </div>
        </CardContent>
      </Card>

      {/* Actions */}
      <div className="grid md:grid-cols-2 gap-4">
        <Card className="shadow-md">
          <CardContent className="pt-6">
            <div className="text-center space-y-3">
              <MapPin className="w-8 h-8 mx-auto text-primary" />
              <h3 className="font-medium">Find Medical Help</h3>
              <p className="text-sm text-muted-foreground">
                Locate nearby dermatologists and medical facilities
              </p>
              <Button onClick={onFindMedicalHelp} className="w-full">
                <MapPin className="w-4 h-4 mr-2" />
                Find Dermatologists
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-md">
          <CardContent className="pt-6">
            <div className="text-center space-y-3">
              <FileText className="w-8 h-8 mx-auto text-primary" />
              <h3 className="font-medium">Save Report</h3>
              <p className="text-sm text-muted-foreground">
                Download your screening report as PDF
              </p>
              <div className="flex gap-2">
                <Button onClick={handleDownloadReport} variant="outline" className="flex-1">
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </Button>
                <Button 
                  onClick={() => {
                    if (navigator.share) {
                      navigator.share({
                        title: 'Skin Screening Report',
                        text: 'My skin cancer screening report',
                        url: window.location.href
                      });
                    }
                  }}
                  variant="outline" 
                  className="flex-1"
                >
                  <Share2 className="w-4 h-4 mr-2" />
                  Share
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Medical Disclaimer */}
      <Card className="shadow-md bg-amber-50 dark:bg-amber-950 border-amber-200 dark:border-amber-800">
        <CardContent className="pt-6">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
            <div>
              <h4 className="font-medium text-amber-800 dark:text-amber-200 mb-2">
                Important Medical Disclaimer
              </h4>
              <p className="text-sm text-amber-700 dark:text-amber-300 leading-relaxed">
                {reportData.disclaimer}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Bottom Actions */}
      <div className="flex justify-center gap-4 pt-4">
        <Button onClick={onNewScreening} variant="outline" size="lg">
          New Screening
        </Button>
        <Button onClick={onFindMedicalHelp} size="lg">
          <Phone className="w-4 h-4 mr-2" />
          Contact Healthcare Provider
        </Button>
      </div>
    </motion.div>
  );
}